# Generated by Django 3.2.8 on 2021-10-27 10:49

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to=products.models.Product.nameFile)),
            ],
        ),
    ]
